# importing the module
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api.formatters import SRTFormatter

# retrieve the available transcripts
transcript_list = YouTubeTranscriptApi.list_transcripts('Ii7x4mpIhIs&t=4s')

formatter = SRTFormatter()

# iterate over all available transcripts
for transcript in transcript_list:
    # the Transcript object provides metadata
    # properties
    print(
        # transcript.video_id,
        # transcript.language,
        # transcript.language_code,

        # whether it has been manually created or
        # generated by YouTube
        # transcript.is_generated,

        # whether this transcript can be translated
        # or not
        # transcript.is_translatable,

        # a list of languages the transcript can be
        # translated to
        transcript.translation_languages,
    )

    # fetch the actual transcript data
    # print(transcript.fetch())

    # 译本文本
    # 原字幕文本
    zh_hans = transcript.translate('zh-Hans').fetch()
    srt_zh_hans_formatted = formatter.format_transcript(zh_hans)
    print('srt_zh_hans_formatted', srt_zh_hans_formatted)
    with open("subtitles.srt", "w") as f:
        # iterating through each element of list srt
        f.write(srt_zh_hans_formatted)
        # for i in srt_zh_hans_formatted:
        #     # writing each element of srt on a new line
        #     f.write("{}\n".format(i))

# you can also directly filter for the language you are
# looking for, using the transcript list
transcript = transcript_list.find_transcript(['en'])

# or just filter for manually created transcripts
transcript = transcript_list.find_manually_created_transcript(['en'])

